### ISSUE TITLE
uvoz zemljevida

### ISSUE THREAD

**Issue by NadjaLegan** [NadjaLegan/APPR-2015-16#2]
Pri uporabi funkcije uvozi.zemljevid, mi javi napako:

```
Error in download.file(url, zip) : 
  cannot open destfile '../zemljevidi/79d7f8be20eda9d9528418f550839c7057048640/79d7f8be20eda9d9528418f550839c7057048640.zip', reason 'No such file or directory'
In addition: Warning message:
In dir.create(map, recursive = TRUE) :
  cannot create dir '..', reason 'Permission denied'
```

To napako mi javi samo na domačem računalniku, na šolskem računalniku mi je normalno uvozilo, prosim za pomoč pri odpravi napake.

**Comment by jaanos** [comment]
Izgleda, da program ni mogel narediti mape `zemljevidi` znotraj mape nad trenutno. Poskrbi, da lahko vanjo pišeš - po potrebi torej premakni celotno mapo s tvojim projektom in v RStudiu odpri datoteko s končnico `.Rproj` znotraj nje. Pazi seveda, da imaš svoj projekt odprt kot tak v RStudiu (če nimaš, klikni desno zgoraj, kjer piše _Project: (None)_, izberi _Open Project..._ in poišči datoteko s končnico `.Rproj`).

Če še vedno ne bi šlo, bi koristilo, če poveš, kateri operacijski sistem uporabljaš, ter kje se nahaja tvoj projekt - to lahko dobiš tako, da ga odpreš v RStudiu in poženeš ukaz `getwd()`.

**Comment by NadjaLegan** [comment]
Hvala za pomoč, sem premaknila celotno mapo s projektom in sedaj dela.
