### ISSUE TITLE
analiza podatkov

### ISSUE THREAD

**Issue by NadjaLegan** [NadjaLegan/APPR-2015-16#3]
Potrebujem pomoč pri analizi podatkov. Ali je dovolj, če naredim grupiranje podatkov po regijah, saj glede na moje podatke ne morem primerjati dveh različnih številskih spremenljivk? Ali je možna primerjava tudi med neštevilsko in številsko spremenljivko?

**Comment by jaanos** [comment]
Kolikor vidim, imaš v svojih razpredelnicah številske podatke za več različnih kategorij. Grupiranje po regijah bi seveda šlo, lahko pa bi načeloma tudi primerjala različne podatke za isto regijo oz. državo (npr. korelacije med dvema podatkoma, ali prikaz in napoved nekega podatka skozi čas).

Kaj natanko imaš v mislih s primerjavo med neštevilsko in številsko spremenljivko? Tukaj je načeloma možno prikazovati kakšna grupiranja; če imamo urejenostno spremenljivko, bi se na nek način dalo tudi delati modele. Kakor rečeno, pa v tvojih podatkih ne vidim neštevilskih spremenljivk, tako da kaj takega najbrž ne pride v upštev.

**Comment by jaanos** [comment]
Mimogrede, opažam, da pri uvozu nimaš pravilno nastavljenega kodiranja znakov. Da bo to pravilno, pri funkcijah `read.csv2` namesto parametra `encoding` podaj parameter `fileEncoding`.

**Comment by NadjaLegan** [comment]
Zdaj sem probala primerjati podatke o izdatkih in številu turistov, ki sem jih združila v TABELA1, vednar ne vem točno kako bi to naredila. Ne vem, kaj bi drugega sploh lahko analizirala, ali imate mogoče kakšen predlog?

**Comment by jaanos** [comment]
Za začetek si lahko izrišeš graf, ki ti prikaže, kako se spremenljivki povezujeta:

``` R
TABELA1 <- inner_join(izdatki, razlog_prihoda)
ggplot(TABELA1, aes(x = Število, y = Izdatek)) + geom_point()
```

Sedaj se lahko malo igraš s podatki - morda lahko filtriraš po kategorijah, da vidiš, kaj se dogaja, ter izločiš osamelce (podatke, ki izstopajo - te lahko pojasniš v poročilu). Lahko si pomagaš tudi z označevanjem točk po kategorijah - če k `aes` dodaš npr. parameter `col = Država`, ti bo točke pobarvalo glede na državo. Tako se lahko potem odločiš, kaj želiš prikazati, in na grafu prikažeš model, ki kaže na odvisnost med podatki (poglej si funkcijo `geom_smooth` - nekaj primerov smo naredili tudi na vajah).

Še to: trenutno vse manjkajoče podatke nadomestiš z ničlami, kar pa ni v redu, saj potem na grafu dobiš točke s koordinato 0, ki niso reprezentativne - zaradi tega je potem tudi zgrajeni model lahko neustrezen. Manjkajoči podatki naj bodo predstavljeni z vrednostjo `NA` - tako se neka točka na grafu ne bo prikazala, če niso znani vsi potrebni podatki.

**Comment by NadjaLegan** [comment]
Aha, bom tako naredila.

Problem pri podatkih je, če dam NA (kar sem na začetku naredila), da mi potem noče narisati grafa. Napiše mi:

`Error in seq.default(from = best$lmin, to = best$lmax, by = best$lstep) : 
  'from' must be of length 1
`

Imam pa še en problem pri zemljevidu sveta, ki sem ga uvozila, da bi lahko narisala zemljevid Evrope (prav posebaj Evrope nisem našla), kako naj filtriram podatke, da bo vzelo samo tiste države, ki jih potrebujem. Poizkusila sem tako:

```
`zemljevid2 <- uvozi.zemljevid("http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_countries.zip",
                        "ne_110m_admin_0_countries") 

Drzave <- levels(prihodkiEU$Država)
EU <- pretvori.zemljevid(zemljevid2)
NOV <- EU %>% filter(name %in% Drzave)`
```

vendar ne deluje.

**Comment by jaanos** [comment]
Kako pa rišeš graf? Sem poskusil nadomestiti vse ničle z `NA`, pa zgornji način še vedno deluje.

Kar se zemljevida tiče, je princip v redu - problem je v tem, da se vsa imena iz tabele ne ujemajo s tistimi v zemljevidu. V samem zemljevidu je sicer tudi podatek o celini, tako da lahko tega uporabiš (le da Turčije ne šteje v Evropo, zato še vedno koristi tvoj seznam):

``` R
NOV <- EU %>% filter(continent == "Europe" | name %in% Drzave)
ggplot() + geom_polygon(data = NOV, aes(x = long, y = lat, group = group)) +
  xlim(-25, 45) + ylim(35, 75)
```

Seveda bo treba ugotoviti, katera imena iz seznama se ne ujemajo, ter jih spremeniti, da boš lahko podatke prikazala na zemljevidu.

**Comment by NadjaLegan** [comment]
Graf imam naprimer narisan tako:

```
GRAF1 <- ggplot(razlog_prihoda %>% group_by(Čas, Država) %>% summarise(Število = sum(Število)),
                aes(x=Čas, y=Število, fill=Država)) + 
  geom_bar(stat = "identity",position="dodge")+
  scale_y_continuous(labels=function(n){format(n, scientific = FALSE)}) +
  labs(title ="Število turistov glede na čas in državo prebivališča")+
  theme_bw() 
```

In mi ga ne izriše v primeru, ko imam NA v zadnjem stolpcu.

**Comment by jaanos** [comment]
Problem je v tem, ker vrednosti seštevaš in potem dobiš `NA` za celotno kategorijo. Da se temu izogneš, pri `sum` dodaj parameter `na.rm = TRUE`.
